### ISSUE TITLE
Add organization README

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/.github#1]
(thanks to for the heads up)

From [GitHub](https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/):

> Start with creating a .github repository for the desired organization. Make sure it's public. Add a profile folder to your .github repository and add a README.md file to the profile folder.

### What to put on there:
- [ ] A welcome message
- [ ] Probably the full logo
- [ ] Some short FAQs (what is this, how do I join, etc)
- [ ] Links to resources like Code of Conduct, Contributing Guide, links to the website
- [ ] A section about sponsorship
- Anything else?

### Resources:
- [Customizing your organization's profile](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile)
- [GitHub's Org README](https://github.com/github)

**Comment by abbeyperini** [comment]
I'll take a look at it today!

**Comment by danieltott** [comment]
Thanks @abbeyperini !!

I'm open to suggestions/design ideas/etc here. No need to overcomplicate or over-design, but it'll be great to have this set up!

**Comment by abbeyperini** [comment]
I think this is a good starting point! Will not be offended if people see it and think of a better design/more content.

**Comment by danieltott** [comment]
closed via #2
