### ISSUE TITLE
Update how to become a member section

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/.github#4]
Since the process for membership has changed, we need it updated. The updated process is on the [About page](https://virtualcoffee.io/about).

**Comment by AlexVCS** [comment]
Are you talking about updating the section on the homepage that reads this way:

Anyone can join! Whether you're thinking about getting into tech or have been in it for decades.

Or are you talking about another part of the site that talks about becoming a member?

**Comment by AlexVCS** [comment]
oh maybe it's the readme inside the profile
